export enum ActionTypes {
    REGISTER = `[Auth] REGISTER`,
    REGISTER_SUCCESS = `[Auth] REGISTER_SUCCESS`,
    REGISTER_FAILURE = `[Auth] REGISTER_FAILURE`,

    LOGIN = `[Auth] LOGIN`,
    LOGIN_SUCCESS = `[Auth] LOGIN_SUCCESS`,
    LOGIN_FAILURE = `[Auth] LOGIN_FAILURE`,

    GET_CURRENT_USER = `[Auth] GET_CURRENT_USER`,
    GET_CURRENT_USER_SUCCESS = `[Auth] GET_CURRENT_USER_SUCCESS`,
    GET_CURRENT_USER_FAILURE = `[Auth] GET_CURRENT_USER_FAILURE`,
}
