export enum ActionTypes {
    REGISTER = `[Auth] REGISTER`,
    REGISTER_SUCCESS = `[Auth] REGISTER_SUCCESS`,
    REGISTER_FAILURE = `[Auth] REGISTER_FAILURE`,

    LOGIN = `[Auth] LOGIN`,
    LOGIN_SUCCESS = `[Auth] LOGIN_SUCCESS`,
    LOGIN_FAILURE = `[Auth] LOGIN_FAILURE`,
}
